# Generated by Django 3.1.2 on 2021-04-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('foreign_key', models.BooleanField(default=False, verbose_name='判断是否存在虚拟表关联')),
                ('ban_foreign_key', models.BooleanField(default=False, verbose_name='如果为true 则此表不允许被再次关联')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '表分类',
                'verbose_name_plural': '表分类',
            },
        ),
        migrations.CreateModel(
            name='DataBind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('source_asset_id', models.BigIntegerField(verbose_name='源资产id')),
                ('target_asset_id', models.BigIntegerField(verbose_name='目标资产id')),
                ('table_bind_id', models.IntegerField(verbose_name='绑定的table_bind_id')),
            ],
            options={
                'verbose_name': '数据关联',
                'verbose_name_plural': '数据关联',
            },
        ),
        migrations.CreateModel(
            name='TableBind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('source_id', models.IntegerField(verbose_name='源ID')),
                ('target_id', models.IntegerField(verbose_name='目标ID')),
                ('multi', models.BooleanField(default=True, verbose_name='判断是否一对多')),
            ],
            options={
                'verbose_name': '模型关联表',
                'verbose_name_plural': '模型关联表',
            },
        ),
        migrations.CreateModel(
            name='DataValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('value', models.JSONField(verbose_name='数据值')),
                ('deleted', models.BooleanField(default=False)),
                ('classify_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.classify', verbose_name='关联Classify')),
            ],
            options={
                'verbose_name': '表字段',
                'verbose_name_plural': '表字段',
            },
        ),
        migrations.CreateModel(
            name='DataMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='中文名称')),
                ('alias', models.CharField(max_length=32, unique=True, verbose_name='英文名称')),
                ('fields', models.JSONField(verbose_name='字段字典')),
                ('meta', models.JSONField(verbose_name='字段元数据')),
                ('deleted', models.BooleanField(default=False)),
                ('classify_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cmdb.classify', verbose_name='关联Classify')),
            ],
            options={
                'verbose_name': '表字段',
                'verbose_name_plural': '表字段',
            },
        ),
    ]
