# Generated by Django 3.1.2 on 2021-04-20 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='中文名称')),
                ('alias', models.CharField(max_length=32, unique=True, verbose_name='英文名称')),
                ('fields', models.JSONField(verbose_name='字段字典')),
                ('meta', models.JSONField(verbose_name='字段元数据')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '表字段',
                'verbose_name_plural': '表字段',
            },
        ),
        migrations.CreateModel(
            name='DataRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('parent_asset_id', models.BigIntegerField(verbose_name='主资产id')),
                ('child_asset_id', models.BigIntegerField(verbose_name='子资产id')),
                ('table_relation_id', models.IntegerField(verbose_name='绑定的table_bind_id')),
            ],
            options={
                'verbose_name': '数据关联',
                'verbose_name_plural': '数据关联',
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('foreign_key', models.BooleanField(default=False, verbose_name='判断是否存在虚拟表关联')),
                ('ban_foreign_key', models.BooleanField(default=False, verbose_name='如果为true 则此表不允许被再次关联')),
                ('pid', models.IntegerField(verbose_name='主表ID,为0则为主类表, 主类表不可绑定虚拟表')),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '表分类',
                'verbose_name_plural': '表分类',
            },
        ),
        migrations.CreateModel(
            name='TableRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('parent_schema_id', models.IntegerField(verbose_name='主schemaID')),
                ('child_schema_id', models.IntegerField(verbose_name='子schemaID')),
                ('is_multi', models.BooleanField(default=True, verbose_name='判断是否一对多')),
            ],
            options={
                'verbose_name': '模型关联表',
                'verbose_name_plural': '模型关联表',
            },
        ),
        migrations.DeleteModel(
            name='DataBind',
        ),
        migrations.RemoveField(
            model_name='datamap',
            name='classify_id',
        ),
        migrations.DeleteModel(
            name='TableBind',
        ),
        migrations.RemoveField(
            model_name='datavalue',
            name='classify_id',
        ),
        migrations.DeleteModel(
            name='Classify',
        ),
        migrations.DeleteModel(
            name='DataMap',
        ),
        migrations.AddField(
            model_name='datafield',
            name='schema_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cmdb.schema', verbose_name='关联Classify'),
        ),
        migrations.AddField(
            model_name='datavalue',
            name='schema_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cmdb.schema', verbose_name='关联的schema_id'),
            preserve_default=False,
        ),
    ]
