# Generated by Django 3.1.2 on 2021-05-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableclassify',
            name='alias',
            field=models.CharField(max_length=32, unique=True, verbose_name='别名'),
        ),
    ]
