# Generated by Django 3.1.2 on 2021-04-20 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20210420_0010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataValue',
            new_name='AssetData',
        ),
        migrations.RenameModel(
            old_name='DataRelation',
            new_name='AssetRelation',
        ),
        migrations.RenameModel(
            old_name='DataField',
            new_name='FieldData',
        ),
    ]
