# Generated by Django 3.1.2 on 2021-05-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20210524_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerecord',
            name='operator',
            field=models.CharField(default='Agent', max_length=64, verbose_name='操作用户'),
        ),
        migrations.AddField(
            model_name='tableclassify',
            name='record_log',
            field=models.BooleanField(default=False, verbose_name='是否记录日志'),
        ),
        migrations.AlterField(
            model_name='tableclassify',
            name='is_forbid_bind',
            field=models.BooleanField(default=False, verbose_name='是否允许绑定'),
        ),
    ]
