# Generated by Django 3.1.2 on 2021-05-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20210527_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changerecord',
            old_name='asset_id',
            new_name='table_data',
        ),
    ]
