# Generated by Django 3.1.2 on 2021-04-20 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20210420_0013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FieldData',
            new_name='FieldMap',
        ),
    ]
