# Generated by Django 3.1.2 on 2021-05-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_tableclassify_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableclassify',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='cmdb/icon/%Y/%m/%d/'),
        ),
    ]
