# Generated by Django 3.1.2 on 2021-04-19 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roles',
            table='rbac_roles',
        ),
    ]
